// <auto-generated />
using LocalBusinessTrackerAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusinessTrackerAPI.Migrations
{
    [DbContext(typeof(LocalBusinessTrackerAPIContext))]
    [Migration("20200403184127_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LocalBusinessTrackerAPI.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Description");

                    b.Property<string>("Hours");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<int>("Rating");

                    b.Property<string>("Type");

                    b.Property<string>("Website");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Address = "126 SW 2nd Ave",
                            Description = "Spanish Style Rotissere Chicken, Specialty Cocktails and Tapas",
                            Hours = "Everyday 11AM to 10PM",
                            Name = "Pollo Bravo",
                            Phone = "503.477.8899",
                            Rating = 5,
                            Type = "Restaurant",
                            Website = "http://www.pollobravopdx.com/"
                        },
                        new
                        {
                            LocationId = 2,
                            Address = "2216 NE MLK Blvd",
                            Description = "A Springboard for Bad Decisions",
                            Hours = "Everyday NOON to 2AM",
                            Name = "Billy Rays Neighborhood Dive",
                            Phone = "503.287.7254",
                            Rating = 4,
                            Type = "Bar",
                            Website = "none"
                        },
                        new
                        {
                            LocationId = 3,
                            Address = "8630 N Lombard St.",
                            Description = "Taqueria, Bakery and Grocery Store in St. Johns",
                            Hours = "Everyday 11AM to 10PM",
                            Name = "Tienda Santa Cruz",
                            Phone = "503.286.7302",
                            Rating = 4,
                            Type = "Restaurant",
                            Website = "none"
                        },
                        new
                        {
                            LocationId = 4,
                            Address = "720 SE Sandy Blvd",
                            Description = "Specialty Cocktail Lounge",
                            Hours = "Everyday 4 to 2AM",
                            Name = "Rum Club",
                            Phone = "503.265.8807",
                            Rating = 5,
                            Type = "Bar",
                            Website = "rumclubpdx.com"
                        },
                        new
                        {
                            LocationId = 5,
                            Address = "5202 N Albina Ave",
                            Description = "Small Independent Record Store and Label",
                            Hours = "Everyday 12PM to 7PM",
                            Name = "Mississippi Records",
                            Phone = "503.282.2990",
                            Rating = 5,
                            Type = "Retail",
                            Website = "none"
                        },
                        new
                        {
                            LocationId = 6,
                            Address = "720 N Killingsworth  St.",
                            Description = "Used, Vintage, & Consignment Store",
                            Hours = "THU - TUE 11AM - 6PM",
                            Name = "Zero Wave",
                            Phone = "971.266.3492",
                            Rating = 4,
                            Type = "Retail",
                            Website = "none"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
